//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CAR()
        {
            this.TB_TRANSACTIONS = new HashSet<TB_TRANSACTIONS>();
        }
    
        public int ID_CAR { get; set; }
        public Nullable<int> ID_CAR_MODEL { get; set; }
        public Nullable<int> ID_CAR_COLOR { get; set; }
        public Nullable<int> ID_CAR_CONDITION { get; set; }
        public Nullable<int> ID_CAR_COUNTRY { get; set; }
        public Nullable<decimal> CAR_PRICE { get; set; }
    
        public virtual TB_CAR_COLOR TB_CAR_COLOR { get; set; }
        public virtual TB_CAR_CONDITION TB_CAR_CONDITION { get; set; }
        public virtual TB_CAR_COUNTRY TB_CAR_COUNTRY { get; set; }
        public virtual TB_CAR_MODEL TB_CAR_MODEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TRANSACTIONS> TB_TRANSACTIONS { get; set; }

    }
}
