//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRANSACTIONS
    {
        public int ID_TRANSACTION { get; set; }
        public int ID_CLIENT { get; set; }
        public int ID_CAR { get; set; }
        public System.DateTime TRANSACTION_DATE { get; set; }
    
        public virtual TB_CAR TB_CAR { get; set; }
        public virtual TB_CLIENT TB_CLIENT { get; set; }
    }
}
